on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Release Build

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Nuget.exe
        uses: NuGet/setup-nuget@v1

      - name: Nuget Restore 
        run: nuget restore .\FriendlySetTime.sln

      - name: Build (DotNET4.6.2)
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe "${{ github.workspace }}\source\Riot.sln" -p:Configuration=Release -restore

      - name: Setup Playnite
        run: |
           Invoke-WebRequest -Uri "https://github.com/JosefNemec/Playnite/releases/download/10.19/Playnite1019.zip" -OutFile "${{ github.workspace }}\Playnite.zip"
           Expand-Archive "${{ github.workspace }}\Playnite.zip" -DestinationPath "${{ github.workspace }}\Playnite"

      - name: Pack with Playnite
        run: |
           cd "${{ github.workspace }}\Playnite"
           .\Toolbox.exe pack "${{ github.workspace }}\bin\Release\" "${{ github.workspace }}\"
           cd "${{ github.workspace }}"
           Get-ChildItem -Filter *.pext | Rename-Item -NewName "Riot-Library_${{ github.ref_name }}.pext"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: false
          files: |
            *.pext